/* eslint-disable prettier/prettier */
import {StyleSheet, Dimensions} from 'react-native';
// export const blackcolor = '#000000';
export const off_white = '#F6F6F6';
export const whitecolor = '#ffffff';
export const graycolor = '#e4e3e3';
export const Dark_graycolor = '#63666A';
export const blackcolor = '#000000';
export const bluecolor = '#0c71cc';
export const medium_gray = '#D3D3D3';
export const light_yellow = '#EADF0C';
export const light_gray = '#cccccc5e';
export const gllery_background = '#2c2c2c';
export const lightgllery_background = '#656565';

export const Dark_Gray = '#A9A9A9';

const screenHeight = Dimensions.get('window').height;
export const SLIDER_WIDTH = Dimensions.get('window').width;
export const ITEM_WIDTH = Math.round(SLIDER_WIDTH);

export const commonstyles = StyleSheet.create({
  HomeThreeCategoryview: {
    borderBottomColor: graycolor,
    borderBottomWidth: 1,
    paddingBottom: 10,
  },
  homecategoryView: {
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  homegallerycategoryView: {
    justifyContent: 'space-between',
    flexDirection: 'row',
    paddingHorizontal: 12,
    alignItems: 'center',
    paddingTop: 12,
    marginBottom: 6,
  },
  homeVideoTextView: {
    width: '100%',
  },
  homevideocategorytext: {
    color: whitecolor,
    fontFamily: 'Mukta-SemiBold',
    fontSize: 22,
    paddingLeft: 10,
  },
  homeVideoview: {
    backgroundColor: gllery_background,
  },
  HomeVideotext: {
    color: whitecolor,
    fontFamily: 'Mukta-SemiBold',
    fontSize: 18,
    lineHeight: 26,
    marginTop: 8,
    marginBottom: 4,
  },
  homephotosliderTextView: {
    width: '100%',
  },
  homeVideosliderText: {
    color: whitecolor,
    fontFamily: 'Mukta-SemiBold',
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '600',
    marginTop: 10,
  },
  homephotosliderText: {
    color: whitecolor,
    fontFamily: 'Mukta-SemiBold',
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '600',
    marginTop: 12,
  },

  HomephotosliderImg: {
    height: 100,
    width: '100%',
    objectFit: 'cover',
    borderRadius: 6,
  },
  HomeVideoImg: {
    // height: 250,
    width: ITEM_WIDTH - 25,
    borderRadius: 6,
    marginBottom: 6,
    objectFit: 'cover',
    aspectRatio: 16 / 9,
  },
  HomeVideosliderImg: {
    height: 110,
    width: '100%',
    borderRadius: 6,
    objectFit: 'cover',
  },

  sectionTitle: {
    marginLeft: 12,
    marginVertical: 12,
    height: 30,
  },
  HomeoneCategoryview: {
    paddingBottom: 10,
    position: 'relative',
  },
  HomeCategoryImg: {
    height: 230,
    width: '100%',
    borderRadius: 6,
  },
  HomeCategorytext: {
    color: whitecolor,
    fontFamily: 'Mukta-Bold',
    fontSize: 20,
    lineHeight: 30,
    fontWeight: '600',
  },
  HomeThreeCategorytext: {
    color: blackcolor,
    fontFamily: 'Mukta-SemiBold',
    fontSize: 16,
    lineHeight: 22,
    paddingTop: 12,
    fontWeight: '500',
  },
  homeFoursliderText: {
    color: blackcolor,
    fontFamily: 'Mukta-SemiBold',
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '600',
    marginTop: 12,
  },
  HomeFourcategoryView: {
    marginTop: 12,
    width: 180,
  },
  DetailsCompOneView: {
    width: 200,
    marginBottom: 12,
  },
  categoryoneTextView: {
    width: '100%',
  },
  CategoryOnetext: {
    color: blackcolor,
    fontFamily: 'Mukta-SemiBold',
    fontSize: 18,
    lineHeight: 26,
    marginTop: 12,
  },
  homeOnetextView: {},
  DetailsShareimage: {width: 30, height: 30},
  DetailsShareview: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: medium_gray,
    flex: 1,
    alignItems: 'center',
  },
  detailauthor: {
    color: blackcolor,
    fontFamily: 'Mukta-SemiBold',
    fontSize: 14,
    marginRight: 12,
  },
  categoryText: {
    fontSize: 22,
    lineHeight: 34,
    color: blackcolor,
    fontFamily: 'Mukta-SemiBold',
    fontWeight: '600',
  },
  bookmarkcategoryText: {
    fontSize: 16,
    color: blackcolor,
    fontFamily: 'Mukta-SemiBold',
  },
  morevideos: {
    width: '100%',
    height: 200,
    resizeMode: 'cover',
  },
  THighliet: {
    width: 80,
    marginLeft: 'auto',
  },
  shareMview: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    flex: 1,
    marginTop: 10,
    marginBottom: 10,
    width: 80,
    marginLeft: 'auto',
  },
  imgview: {marginRight: 8, marginTop: 4},
  shareimage: {height: 18, width: 18, color: Dark_Gray, resizeMode: 'contain'},
  shareview: {marginRight: 15},
  sharetext: {color: Dark_Gray, fontSize: 16, fontWeight: '500'},
  settingimg: {width: 20, height: 20, color: blackcolor},
  settingtext: {
    color: blackcolor,
    fontSize: 16,
    marginLeft: 16,
    fontWeight: '600',
  },
  scroll: {backgroundColor: whitecolor},
  TextView: {
    flexDirection: 'row',
    flex: 2,
    fontFamily: 'Mandali-Regular',
    fontSize: 20,
    lineHeight: 33,
    justifyContent: 'center',
  },
  Textdot: {
    marginTop: 10,
  },
  HomeCateImg: {
    height: 200,
    width: ITEM_WIDTH - 30,
    borderRadius: 15,
  },
  categorytwoText: {
    color: blackcolor,
    fontSize: 16,
    fontFamily: 'Mukta-SemiBold',
  },
  catecomp2mainView: {borderBottomColor: medium_gray, borderBottomWidth: 2},
  catecomp2Tochable: {flexDirection: 'row', display: 'flex'},

  cateview: {marginTop: 7, flex: 0.7},
  CategoryOneview: {},
  CategoryOneImg: {
    height: 200,
    width: '100%',
    borderRadius: 6,
  },
  HomeComp2DotView: {
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomColor: medium_gray,
    borderBottomWidth: 1.5,
    paddingVertical: 12,
  },
  HomeComp2MainView: {
    flexDirection: 'column',
    alignItems: 'flex-start',
  },
  HomeComp2Text: {
    color: blackcolor,
    fontFamily: 'Mandali-Bold',
    fontSize: 18,
    lineHeight: 31,
    marginLeft: 5,
    justifyContent: 'center',
  },
  Homecartoonimg: {
    width: Dimensions.get('window').height * 0.4,
    borderRadius: 10,
    resizeMode: 'contain',
    margin: 5,
    aspectRatio: 3 / 4,
  },
  HomePhotoimgOne: {
    width: Dimensions.get('window').height * 0.4,
    borderRadius: 10,
    resizeMode: 'contain',
    margin: 5,
    height: Dimensions.get('window').height - 500,
  },
  HomePhotoimgTwo: {
    width: Dimensions.get('window').height * 0.2,
    borderRadius: 10,
    resizeMode: 'contain',
    margin: 5,
    aspectRatio: 3 / 3,
  },

  container: {
    width: '100%',
    height: '100%',
    backgroundColor: whitecolor,
  },
  spinnerView: {justifyContent: 'center', alignItems: 'center', flex: 1},
  spinnerText: {fontSize: 16, textAlign: 'center', color: blackcolor},
  loader: {
    marginTop: 10,
    alignItems: 'center',
  },
  cateMView: {
    flexDirection: 'row',
    left: 10,
    marginRight: 10,
    flex: 2,
  },
  menuview: {
    alignItems: 'center',
    marginRight: 10,
    left: 20,
  },
  menutext: {
    paddingHorizontal: 10,
    textAlign: 'center',
    textAlignVertical: 'center',
    color: blackcolor,
    fontSize: 22,
    fontFamily: 'Mandali-Bold',
  },
  latestMainView: {width: Dimensions.get('window').width, margin: 5},
  latestsubView: {
    backgroundColor: whitecolor,
    height: 155,
    borderRadius: 10,
  },
  VideoimgTag: {
    width: '100%',
    height: 200,
    borderRadius: 5,
  },
  PhotoimgTag: {
    width: '100%',
    height: 200,
    borderRadius: 5,
    paddingTop: 10,
  },
  HomeVideoCategoryview: {
    paddingBottom: 12,
  },
  galleryArticlecategorytext: {
    color: bluecolor,
    fontSize: 20,
    fontFamily: 'Mukta-Bold',
    fontWeight: '700',
  },
  latestTxtTag: {
    color: blackcolor,
    fontFamily: 'Mukta-SemiBold',
    fontSize: 16,
    lineHeight: 24,
    marginVertical: 10,
    fontWeight: '600',
  },
  slidercard: {
    width: ITEM_WIDTH - 150,
    height: 200,
    borderRadius: 5,
    objectFit: 'fill',
  },
  photocard: {
    height: Dimensions.get('window').height * 0.32,
    resizeMode: 'contain',
    aspectRatio: 9 / 9,
    borderRadius: 5,
  },
  videocard: {
    height: Dimensions.get('window').height * 0.32,
    resizeMode: 'contain',
    aspectRatio: 10 / 9,
    borderRadius: 5,
  },
  pagination: {
    position: 'relative',
  },
  slidertext: {
    color: whitecolor,
    fontFamily: 'Mukta-Bold',
    fontSize: 16,
    lineHeight: 20,
    position: 'absolute',
    padding: 12,
  },
  photoview: {
    backgroundColor: graycolor,
    borderRadius: 10,
    margin: 5,
    width: '97%',
    paddingBottom: 10,
    marginTop: 10,
    paddingTop: 10,
  },
  phototextview: {
    flexDirection: 'row',
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 10,
    flex: 1,
  },
  ptext: {
    color: whitecolor,
    fontSize: 25,
    marginEnd: 5,
    fontFamily: 'Mandali-Bold',
  },
  phototext: {
    color: blackcolor,
    fontFamily: 'Mandali-Bold',
    fontSize: 22,
    marginLeft: 10,
    marginRight: 10,
    lineHeight: 29,
    position: 'relative',
    top: 25,
  },
  sliderGradient: {
    width: '100%',
    borderBottomLeftRadius: 6,
    borderBottomRightRadius: 6,
    position: 'absolute',
    height: 60,
    backgroundColor: '#000000',
    filter: 'blur({10}px)',
    bottom: 0,
  },
  HomeonesliderGradient: {
    width: '100%',
    bottom: 0,
    left: 0,
    right: 0,
    position: 'absolute',
    padding: 12,
    borderBottomLeftRadius: 6,
    borderBottomRightRadius: 6,
  },
  linearGradient: {
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 5,
    height: 100,
    width: '100%',
    position: 'absolute',
    bottom: 0,
    flex: 1,
    borderBottomLeftRadius: 15,
    borderBottomRightRadius: 15,
  },
  SlidercategoryView: {
    justifyContent: 'space-between',
  },
  SliderflatView: {
    justifyContent: 'center',
    display: 'flex',
    marginTop: 8,
    marginBottom: 12,
  },
  Category: {
    color: bluecolor,
    fontFamily: 'Mukta-Bold',
    fontSize: 20,
    // marginLeft: 12,
    lineHeight: 32,
    fontWeight: '700',
  },
  homeNextImage: {
    right: 4,
  },
  sliderView: {
    position: 'relative',
    backgroundColor: 'transparent',
  },
  dot: {
    marginTop: 22,
    marginLeft: 15,
  },
  latestCard: {
    backgroundColor: '#fff',
    padding: 5,
    elevation: 5,
    margin: 5,
    borderRadius: 10,
    flexDirection: 'row',
    flex: 1,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.7,
    shadowRadius: 2,
  },
  latestImage: {
    width: '100%',
    height: screenHeight * 0.12,
    borderRadius: 10,
  },
  cateView: {flexDirection: 'row', marginLeft: 5, width: '100%'},
  cateImage: {width: 120, height: 80, borderRadius: 6},
  latestText: {
    color: blackcolor,
    fontFamily: 'Mukta-SemiBold',
    fontWeight: '500',
    fontSize: 16,
    lineHeight: 24,
  },
  latesttime: {color: whitecolor, fontSize: 12},
  Homecomp3time: {color: blackcolor, fontSize: 12},

  HomeTwotime: {color: Dark_graycolor, fontSize: 12},
  CategoryOnetime: {color: blackcolor, fontSize: 12},
  CategoryOnetimeview: {
    flexDirection: 'row',
    paddingLeft: 7,
  },
  cardViewFirst: {
    backgroundColor: whitecolor,
    padding: 3,
    elevation: 5,
    margin: 5,
    borderRadius: 10,
    flexDirection: 'row',
    flex: 1,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.7,
    shadowRadius: 2,
  },
  cardView: {
    backgroundColor: whitecolor,
    padding: 3,
    elevation: 5,
    margin: 5,
    borderRadius: 10,
    flexDirection: 'row',
    flex: 1,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.7,
    shadowRadius: 2,
    borderBottomColor: graycolor,
    borderBottomWidth: 2,
    borderLeftColor: graycolor,
    borderLeftWidth: 1,
    borderRightColor: graycolor,
    borderRightWidth: 1,
  },
  latestViewcard: {
    backgroundColor: whitecolor,
    padding: 5,
    elevation: 5,
    margin: 5,
    width: '100%',
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.7,
    shadowRadius: 2,
  },
  cardViewHome: {
    backgroundColor: whitecolor,
    padding: 5,
    elevation: 5,
    margin: 5,
    borderRadius: 10,
    flexDirection: 'row',
    flex: 1,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.7,
    shadowRadius: 2,
    borderBottomColor: graycolor,
    borderBottomWidth: 2,
    borderLeftColor: graycolor,
    borderLeftWidth: 1,
    borderRightColor: graycolor,
    borderRightWidth: 1,
  },
  cinemaText: {
    color: blackcolor,
    fontFamily: 'JIMS',
    fontSize: 22,
    lineHeight: 30,
  },
  SportCard: {
    flex: 1,
    backgroundColor: '#fff',
    elevation: 1,
    margin: 5,
    borderRadius: 5,
    height: 170,
    flexDirection: 'row',
  },
  sportimage: {
    height: Dimensions.get('window').height * 0.12,
    borderRadius: 10,
    resizeMode: 'center',
  },
  CartoonCard: {
    width: '95%',
    justifyContent: 'center',
    flex: 1,
    backgroundColor: '#fff',
    elevation: 1,
    margin: 10,
    borderRadius: 5,
    height: 'auto',
    flexDirection: 'row',
    paddingRight: 10,
  },
  pcard: {
    width: '95%',
    backgroundColor: '#fff',
    elevation: 1,
    margin: 5,
    borderRadius: 5,
    height: Dimensions.get('window').height * 0.32,
    flexDirection: 'row',
  },
  vcard: {
    width: '95%',
    backgroundColor: whitecolor,
    elevation: 1,
    margin: 5,
    borderRadius: 5,
    height: Dimensions.get('window').height * 0.3,
    flexDirection: 'row',
  },
  pimg: {
    width: '98%',
    height: 180,
    borderRadius: 10,
    resizeMode: 'contain',
    margin: 5,
  },
  vimg: {
    width: '96%',
    height: 180,
    borderRadius: 10,
    resizeMode: 'contain',
    margin: 5,
  },
  cartoonimg: {
    width: Dimensions.get('window').height * 0.23,
    borderRadius: 10,
    resizeMode: 'contain',
    margin: 5,
    aspectRatio: 3 / 4,
  },
  photoimage: {
    width: '110%',
    height: Dimensions.get('window').height * 0.13,
    borderRadius: 15,
    resizeMode: 'center',
  },
  SportText: {
    color: blackcolor,
    fontFamily: 'Mandali-Regular',
    fontSize: 18,
  },
  Detailslargecardvideo: {
    height: 200,
    marginTop: 10,
    marginBottom: 10,
    width: '100%',
  },
  Detailslargecard: {
    height: 216,
    width: '100%',
    backgroundColor: blackcolor,
  },
  shortsTime: {
    color: blackcolor,
    fontFamily: 'JIMS',
    fontSize: 12,
  },
  detailsCateName: {
    color: Dark_graycolor,
    fontFamily: 'Mukta-Regular',
    fontSize: 14,
  },
  timeview: {
    flexDirection: 'row',
    top: -5,
  },
  detailTime: {
    color: Dark_graycolor,
    fontSize: 11,
  },
  publishedtext: {
    color: blackcolor,
    fontSize: 11,
    fontFamily: 'Mandali-Bold',
    fontWeight: '800',
  },
  cateviewText: {
    flex: 1,
    marginRight: 12,
  },
  cateflist: {paddingHorizontal: 12},
  photoflist: {paddingHorizontal: 12},

  videoImg: {
    width: Dimensions.get('window').width * 0.3,
    height: Dimensions.get('window').height * 0.2,
    borderRadius: 10,
    resizeMode: 'stretch',
  },
  categoryView: {flex: 1.7, flexDirection: 'row'},
  homeCategoryflatView: {
    position: 'relative',
  },
  bgDarkGrey: {
    width: '100%',
    backgroundColor: '#85929e',
    paddingTop: 10,
    paddingBottom: 10,
    paddingRight: 3,
    paddingLeft: 3,
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
  },
  prevText: {
    color: blackcolor,
    textAlign: 'center',
    fontSize: 18,
    fontFamily: 'RobotoCondensed-Regular',
  },
  prevNextMainView: {
    flexDirection: 'row',
    flex: 1,
    justifyContent: 'space-between',
    marginTop: 5,
    marginBottom: 5,
  },
  prevView: {flex: 0.25, height: 30, justifyContent: 'center', marginLeft: 10},
  nextView: {flex: 0.2, height: 30, justifyContent: 'center', marginRight: 10},
  relatedText: {
    color: '#000',
    fontSize: 20,
    fontFamily: 'RobotoCondensed-Regular',
  },
  photoflash: {
    color: whitecolor,
    fontSize: 20,
    fontFamily: 'RobotoCondensed-Regular',
  },
  nextText: {
    color: blackcolor,
    fontSize: 20,
    fontFamily: 'RobotoCondensed-Regular',
  },
  flashView: {
    backgroundColor: graycolor,
    borderRadius: 10,
    margin: 5,
    width: '97%',
    paddingBottom: 10,
    marginTop: 10,
    paddingTop: 10,
  },
  flashtext: {
    color: whitecolor,
    fontFamily: 'Mandali-Bold',
    fontSize: 22,
    marginLeft: 10,
    marginRight: 10,
    lineHeight: 29,
    position: 'relative',
    top: 25,
  },
  categoryMview: {flexDirection: 'row', bottom: 5, flex: 1},
  moreview: {alignContent: 'flex-end', alignItems: 'flex-end'},
  moretext: {
    fontFamily: 'RobotoCondensed-Regular',
    fontSize: 18,
    color: blackcolor,
  },
  loadingview: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 100,
  },
  loadingtext: {
    fontSize: 16,
    textAlign: 'center',
    color: '#000000',
  },
  horoMainView: {
    alignItems: 'flex-start',
    flexWrap: 'wrap',
    flex: 1,
    margin: 5,
    borderBottomColor: medium_gray,
    borderBottomWidth: 1.5,
  },
  horoimageView: {
    marginRight: 5,
    flexDirection: 'row',
  },
  horoimage: {
    width: 120,
    height: 90,
    borderRadius: 5,
    resizeMode: 'contain',
  },
  horotextView: {flex: 2},
  horotext: {
    color: blackcolor,
    fontFamily: 'Mandali-Bold',
    fontSize: 18,
    lineHeight: 31,
    marginLeft: 5,
    marginVertical: 20,
  },
  horomore: {
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
    alignSelf: 'flex-end',
  },
  horomoretext: {
    fontFamily: 'RobotoCondensed-Regular',
    fontSize: 18,
    color: blackcolor,
  },
  DetailTimeMainView: {
    flexDirection: 'row',
    // borderLeftColor: bluecolor,
    // borderLeftWidth: 6,
    justifyContent: 'space-between',
    paddingLeft: 6,
    alignItems: 'center',
    marginBottom: 10,
    marginTop: 4,
    flexWrap: 'wrap',
  },
  detailauthorgallery: {
    color: whitecolor,
    fontFamily: 'Mukta-SemiBold',
    fontSize: 14,
    marginRight: 12,
  },
  detailTimegallery: {
    color: whitecolor,
    fontSize: 11,
  },
  settingview: {
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomColor: light_gray,
    borderBottomWidth: 1,
  },
  settingmediaview: {
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  settingmediaimg: {width: 25, height: 25},
  settingmediatext: {
    color: blackcolor,
    fontSize: 16,
    marginLeft: 16,
    fontWeight: '600',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  noMoreText: {
    fontSize: 14,
    color: blackcolor,
    textAlign: 'center',
  },
  articleTimeStamp: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 4,
  },
  shareIcon: {width: 16, height: 16},
  iconPress: {padding: 4, borderRadius: 12},
  actionIconSize: {width: 22, height: 22},
  seealltext: {color: bluecolor, fontWeight: '500', fontSize: 16},
  iconRipple: {padding: 12},
  noNextArticles: {
    fontSize: 16,
    color: blackcolor,
    textAlign: 'center',
    marginBottom: 13,
  },
  articleContainer: {paddingLeft: 12, flex: 1, alignItems: 'flex-start'},
  loadMoreBtn: {
    alignSelf: 'center',
    marginVertical: 12,
    paddingHorizontal: 18,
    paddingVertical: 8,
    backgroundColor: bluecolor,
    borderRadius: 30,
    padding: 10,
  },
  loadMoreBtnTxt: {
    color: whitecolor,
    fontWeight: 'bold',
    fontSize: 16,
  },
});
